### ISSUE TITLE
Investigate high performance for well-displaced jets

### ISSUE THREAD

**Issue by matt-komm** [LLPDNNX/XTagger#4]
High separation observed for ctau~1m and beyond. Can this be traced to a single input variable?

**Comment by daiktas** [comment]
Some network input variables with biggest differences for different ctau values. Will investigate further

1. cpf
⋅⋅* drminsv
..* trackSip2dValAboveCharm
..* trackSip2dSigAboveCharm
..* trackSip3dValAboveCharm
..* trackSip3dSigAboveCharm
..* vertex_association
2. npf
..* drminsv
..* puppi_weight
3. sv
..* ...
4. global
..* csv_jetNTracksEtaRel
..* csv_vertexCategory
..* csv_trackSumJetEtRatio
..* csv_trackSumJetDeltaR
..* csv_jetNSelectedTracks
..* csv_trackSip2dValAboveCharm
..* csv_trackSip2dSigAboveCharm
..* csv_trackSip3dValAboveCharm
..* csv_trackSip3dSigAboveCharm
..* nsv

**Comment by daiktas** [comment]
@matt-komm 

Not sure exactly what else could be added here. As discussed, performance might come from correlations of variables and not individual variables themselves. Maybe close this and add another issue with focus on training a network with global (deepCSV variables). Also https://app.zenhub.com/workspace/o/llpdnnx/nanox/issues/10 is a bit of a duplicate.

**Comment by daiktas** [comment]
Aah it's already there :D 
https://app.zenhub.com/workspace/o/llpdnnx/nanox/issues/30

**Comment by matt-komm** [comment]
well the discrimination at high ctau is very very high. Is there one or two variables which completely drive this? if yes we may consider to make some preselection on these variables before the training to put the network into a more complicated region again or even replace the network with a simple list of cuts instead
