### ISSUE TITLE
class proportions matter?

### ISSUE THREAD

**Issue by matt-komm** [LLPDNNX/XTagger#5]
* does the network performance change if background classes are overrepresented? In particular, does the performance for separating LLP vs. all backgrounds degrade?
* instead of cross entropy one may use the entropy between LLP and each background classes added

**Comment by daiktas** [comment]
Reminder for myself -- training submitted @daiktas

**Comment by daiktas** [comment]
Impossible to achieve background overrepresantation in the high-pT region. Imbalance in the low-pT region degrades overall performance for LLP vs b,c,uds,g.

@matt-komm Should we close this? And use class balance wherever possible.

**Comment by matt-komm** [comment]
well, now that their is a lot of signal - maybe you can test instead at which point the tagger degrades when you reduce the amount of signal e.g. (1/2,1/5,1/10,1/20) but keep the background as is

this ticket was motivated by the question if cross entropy is the best loss for us since if the backgrounds are overrepresented or sufficiently to tough to be separated against each other their loss may dominate the total loss -> thus the llp performance is degraded
